### ISSUE TITLE
Is there a quick way to flat source directory when linking to target directory

### ISSUE THREAD

**Issue by younger-1** [SuperCuber/dotter#121]
### Environment
If applicable, provide the following details:
- **OS**: Darwin Kernel Version 21.6.0
- **Dotter version**: dotter 0.12.14
- **Additional relevant information**

### The question
I have this `dotter` source files. I want all the files under bin goto the target directory without sub-directory
```
├── bin/
│  ├── bew/
│  │  ├── bew.md
│  │  ├── blank-lines*
│  │  ├── chronometer
│  │  ├── cli-clipboard-provider
│  │  ├── color256text
│  │  ├── colortest
│  │  └── imgcat*
│  ├── fzf/
│  │  ├── fzf-panes.tmux*
│  │  ├── fzf.md
│  │  └── fzfp*
│  ├── ix.sh*
│  ├── osc52.sh*
│  ├── paste.sh*
│  ├── test.sh*
│  └── util.sh
```

So instead of writing the dotter config like this,
```toml
bin = { target = "~/bin", type = "symbolic" }
```
I can flat it when linking to target directory by write this:
```toml
bin = { target = "~/bin", type = "symbolic" }
"bin/bew" = { target = "~/bin", type = "symbolic" }
"bin/fzf" = { target = "~/bin", type = "symbolic" }
```

This works like a charm! Thanks for your great work! I want to know if there is a way I could do it more efficiently?
Or is it possible to add feature like this:
```toml
# flat all sub dirs, recursively
bin = { target = "~/bin", type = "symbolic", flat_sub_dirs = true }

# (optional) only flat provided sub dirs, recursively
bin = { target = "~/bin", type = "symbolic", flat_sub_dirs = { 'bew', 'fzf' } }
```
