### ISSUE TITLE
[FEATURE] dotter init should be recursive

### ISSUE THREAD

**Issue by KrullBorg** [SuperCuber/dotter#125]
**Is your feature request related to a problem? Please describe.**
For directories `dotter init` makes empty items in default package files section

**Describe the solution you'd like**
I think it should be recursive, considering each directory as a package (as GNU Stow)

For example, this .dotfiles directory 

```
bash/.bashrc
bash/.bash_logout
bash/.profile
emacs/.emacs
openbox/.config/openbox/rc.xml
```

should produce this global.toml

```toml
[default]
depends = []

[default.files]

[default.variables]

[bash]
depends = []

[bash.files]
"bash/.bashrc"="~/.bashrc"
"bash/.bash_logout"="~/.bash_logout"
"bash/.profile"="~/.profile"

[emacs]
depends = []

[emacs.files]
"emacs/.emacs"="~/.emacs"

[emacs.variables]

[openbox]
depends = []

[openbox.files]
"openbox/.config/openbox/rc.xml"="~/.config/openbox/rc.xml"

[openbox.variables]

```
