### ISSUE TITLE
Design solution for multi-platform dotfiles

### ISSUE THREAD

**Issue by SuperCuber** [SuperCuber/dotter#5]
I'd like a way to have the same files deployed to a different location (or maybe not deployed at all) depending on
- platform (windows/linux)
- maybe user input (e.g. I am on on desktop therefore I want a different bar that doesn't contain a battery indicator)
This should work for variables as well I think.

I also want to rethink the way configuration and deployment is done as a whole.

**Comment by SuperCuber** [comment]
My current ideas:
- **Rework the concept of caching** to be instead templating into a directory then *symlinking* the files inside it to their targets outside.
  - The reason for this is that if the template directory is in the same structure as the *source* files, not the *target* files, then it's easier to "diff" between it and the source files and detect file deletions which are currently not handled.
    I also think it's cleaner and easier to understand that way.
  - This means that `nocache` will not be an option anymore.
  - Files that have no variables to template can be symlinked twice in a chain - this is advantageous for files that you might want to edit in the destination location, or files which you want to edit often without running `deploy` every time (for example many small changes to vimrc while experimenting with it)
- The `secrets.toml` concept is not good enough - I want it to also include the ability to:
  - **Change the target of a file**
    For example NeoVim reads the init script from a different location than vim, and it also depends on platform - so you'd override the target depending on your current machine's setup
  - **Enable/disable certain files**
    For example I might bash installed on a certain machine but zsh on another, I don't want to deploy both of them.
  For those things to be possible I might also need to rework how configuration works in general.

**Comment by SuperCuber** [comment]
## Idea for new configuration solution
The configuration will have two files: `global.toml` and `local.toml`.
`global.toml` is inteded to be checked into source control while `local.toml` isn't.

### global.toml
The global configuration will have packages. Each package will have two sections - variables and files.
It's also recommended to specify what that package will expect to exist in `local.toml` which will be explained shortly.

Example:
```toml
# Local files: conky and Xresources
[i3.files]
i3 = "~/.i3/config"
polybar = "~/.config/polybar/config"
compton = "~/.compton.conf"

# Local variables: terminal
[i3.variables]
font = "Ubuntu"
monofont = "Fira Mono"
fontsize = "10"

[bash.files]
bashrc = "~/.bashrc"

[zsh.files]
zshrc = "~/.zshrc"
zprofile = "~/.zprofile"
```

### local.toml
The local configuration file will specify how to apply the global config to this particular machine - in particular, what packages to deploy and what the local values for files and variables are.
Any values here will **override** the configuration in `global.toml`. Additionally, to delete a key from `global.toml`, you can set it to the special value `false`

Example:
```toml
packages = ["i3", "bash"]

# The comment in global.toml reminded us that we need to specify the location of "conky" and "Xresources"
[i3.files]
# In this example I chose to not specify the target of "conky" - it will simply not get deployed
Xresources = "~/.Xresources"
polybar = false  # in this example I don't want the polybar config to be deployed since it's not installed

[i3.variables]
terminal = "xfce4_terminal"
```

### Execution
The program will first read `global.toml`, then `local.toml`'s `packages` variable. It will only keep the selected packages, and then and will **merge** `global.toml` and `local.toml`, giving priority to `local.toml`.

In this example, this will be the resulting configuration:
```toml
[i3.files]
i3 = "~/.i3/config"
# polybar has been disabled in local
compton = "~/.compton.conf"
Xresources = "~/.Xresources"  # from local

[i3.variables]
font = "Ubuntu"
monofont = "Fira Mono"
fontsize = "10"
terminal = "xfce4_terminal"  # from local

[bash.files]
bashrc = "~/.bashrc"

# zsh wasn't selected
```

Finally, all the packages will be merged together, making all variables available to all packages:
```toml
[files]
i3 = "~/.i3/config"
compton = "~/.compton.conf"
Xresources = "~/.Xresources"
bashrc = "~/.bashrc"

[variables]
font = "Ubuntu"
monofont = "Fira Mono"
fontsize = "10"
terminal = "xfce4_terminal"
```
And this configuration will be deployed.
