### ISSUE TITLE
[FEATURE] Conditionally include files

### ISSUE THREAD

**Issue by mythmon** [SuperCuber/dotter#52]
**Is your feature request related to a problem? Please describe.**
I have some packages in my dotfiles that have integrations with other packages. For example, I use both taskwarrior and polybar, though not always both together.  If I have both polybar and taskwarrior, I'd like to include an extra file in the polybar configuration, to be used to show data from taskwarrior.

**Describe the solution you'd like**
It would be nice to be able to say something like
```toml
[polybar.files]
"polybar/taskwarrior.sh" = {
	target = "~/.config/polybar/taskwarrior.sh"
	depends = ["taskwarrior"]
	# or alternatively, some scripted condition
	if = "polybar in dotter.packages"
}
```

**Describe alternatives you've considered**
I could make a seperate package, "polybar-taskwarrior", and include that anytime that I have both set up. That's an extra step though, and not as automatic.
