### ISSUE TITLE
Dynamic self reference

### ISSUE THREAD

**Issue by jakob-kruse** [SuperCuber/dotter#56]
### Environment
Arch Linux
Dotter 0.12.1

### The question
For example, I have the following section in my `.dotter/global.toml`

```toml
[foo.files]
"template" = "template.hbs"

[foo.variables]
"list" = [ "bar", "more-bar" ]
"bar" = "hello"
"more-bar" = "bye"
```

Now in the template file I want to iterate over `foo.list`:

```hbs
{{#each list as | myProp |}}
{{/each}}
```

In that loop i want to get the variable inside foo. For example, `foo[myProp]` (when myProp is "bar") should render "hello".

I thought about using lookup for that, but I can't get it to work.

I tried doing (inside the loop) 
```hbs 
{{ lookup @root.foo myProp }}
```
But that just renders nothing.

The following does work as intended, but the prop cant be dynamic
```hbs
{{ ../prop }}
```

I know this is very specific, I'm sorry. Thanks
