### ISSUE TITLE
[FEATURE] Support program installation

### ISSUE THREAD

**Issue by MiSawa** [SuperCuber/dotter#59]
**Problem**
We can install configurations easily with dotter, very nice! Though I (or we) have many configurations for programs that isn't installed initially. So the next (or previous) step of running dotter would be installing all sorts of programs using an appropriate installer (e.g. `pacman`, `yay`, `apt`, `curl "..." | sh`, `cargo`) and run post-install work (e.g. `chsh`, `systemctl enable`), which is also a tedious work.

**Solution**
It'd be great if dotter also handle program installation. Here is a random example configuration.
```toml
# in global.toml
[zsh.install]
package_name = "zsh" # the argument passed to the installer as a template variable
post_install = "chsh -s $(which zsh)" # a hook ran after installation
pre_uninstall = "chsh -s /usr/bin/bash" # another hook ran before uninstallation

[rustup.install]
installer = "install-rustup" # The installer to use. Falls back to the default one configured in local.toml

[rust]
depends = ["rustup"]

[rust.install]
installer = "rustup"
package_name = "stable"


# in local.toml (or arch.toml, rust.toml or whatever included by local.toml)
[installer]
default = "yay"

[installer.yay]
initialize = "yay -Syyu" # update caches
install_package = "yay -Sy {{package.name}}" # a command template that installs the given package
update_package = "..." # an optional command template that updates the given package
remove_package = "..." # an optional command template that removes the given package
check_installed = "..." # an optional command that checks if the package is already installed
install_packages = "..." # an optional command template that installs the given set of packages, just for speed up

[installer.install-rustup]
install_package = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"

# and other configs
```
When you run `dotter deploy` without caches they should
- check if the needed packages are installed using `check_installed` command for the installer,
- install missing packages using `initialize` and `install_package` (or `install_packages` for common installers) command for each installers,
- run `post_install` hook for installed packages.

Also we can have `dotter deploy --update-packages` which calls `update_package` on all the enabled packages after usual `dotter deploy`.

**Alternative approaches**
In the above example, I have put everything into the configuration toml. Though `installer` configs may be better done with, for example, just a single executable or template of shell script in the repository that does installation, uninstallation, ... according to their argument or environment variable or whatever. Or maybe we can have multiple executables named `install`, `uninstall`, ... in a directory.

**Additional notes**
- I'm really new to dotter, just came across with it today. This could be just an out-of-scope thing. Maybe this should be done with the current equipment, like pre-deploy hooks + helpers. Or maybe there's more sophisticated approach that fits better for dotter.
- Package installation and hooks may require `sudo`, or require `sudo` password interactively, which makes things a bit more complicated. Maybe just redirect stdio of subprocess to console?
- Maybe there's a case we'd like to have a specific version of a package, so it'd make sense to also support `version = "1.2.3"` and `{{version}}`.
