### ISSUE TITLE
[BUG] Included file `windows.toml` can't use more specific key to override

### ISSUE THREAD

**Issue by younger-1** [SuperCuber/dotter#83]
## Environment
- **OS**: Windows version
- **Dotter version**: Dotter 0.12.6
- **Additional relevant information**

## Description
In included file `windows.toml`, I had `[vim.files]` section. It worked when it was:

```toml
[vim.files]
vimrc = { target = "~/_vimrc", type = "symbolic" }
gvimrc = { target = "~/_gvimrc", type = "symbolic" }
```

But it failed when I want to use more specific key to override the vim path

```toml
[vim.files]
vimrc.target = "~/_vimrc"
gvimrc.target = "~/_gvimrc"
```

## Reproduction
Here is my config:
`global.toml`

```toml
[helpers]

[default]
depends = []

[default.files]
"conda.yml" = "~/.condarc"
gitconfig = "~/.gitconfig"

[vim.files]
vimrc = { target = "~/.vimrc", type = "symbolic" }
gvimrc = { target = "~/.gvimrc", type = "symbolic" }

[default.variables]
```

`windows.toml`

```toml
[vim.files]
vimrc.target = "~/_vimrc"
gvimrc.target = "~/_gvimrc"
```

`local.toml`

```toml
includes = [".dotter/windows.toml"]

packages = ["default", "vim"]
```

### Expected behavior
`dotter.exe` should deployed successfully.

### Actual behavior

`dotter.exe` compained when executed `dotter -d deploy`

```log
[ERROR] Failed to deploy
Caused by:
    get a configuration
    merge configuration files
    including file ".dotter/windows.toml"
    load file
    deserialize file contents
    data did not match any variant of untagged enum FileTargetOuterRepr for key `vim.files.vimrc`
```
