### ISSUE TITLE
Is it some way to choose where to use templates?

### ISSUE THREAD

**Issue by z775729168** [SuperCuber/dotter#88]
### Environment
If applicable, provide the following details:
- **OS**:  Windows version
- **Dotter version**: Dotter 0.12.7
- **Additional relevant information**

### The question
Fascinating tool! It's so free.
I try to sync the [espanso](https://github.com/federico-terzi/espanso) config file, but espanso use the same template [syntax](https://espanso.org/docs/matches/#dynamic-matches).
```shell
[ERROR] Failed to create template "espanso\\default.yml" -> "D:\\Program\\apps\\espanso\\current\\.espanso\\default.yml"
Caused by:
    perform template cache
    render template
    Error rendering "Unnamed template" line 24, col 15: Variable "mydate" not found in strict mode.
```

**Comment by SuperCuber** [comment]
You can either use handlebars's solution to it, which if I remember correctly involves `{{{thing}}}`, or mark the whole file as a symlink with

```toml
"espanso/default.yml" = { type = "symbolic", target = "..." }
```

I don't quite remember the code and can't test it but you might encounter a problem with symlinks requiring developer mode on windows - if this prevents you from using symlinks this way please open an issue and enable developer mode in the meantime

**Comment by z775729168** [comment]
Thanks for your relay.
Both solutions don't work unfortunately, but it reminds me that I can use `command_output` to `echo` something.
```yaml
  # Dates
  - trigger: ":date"
    replace: "{{command_output "set /p ={{mydate}}<nul"}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"
```
Works well. Thank you.
